### ISSUE TITLE
Async?

### ISSUE THREAD

**Issue by carols10cents** [ThouCheese/cloud-storage-rs#10]
Would you be open to a pull request adding an async API that uses `reqwest::Client` rather than `reqwest::blocking::Client`? If that's not something you would want to maintain, I understand :)

**Comment by ThouCheese** [comment]
Yes, I would be very much open to such a PR. I think it is necessary to support async with the support it is gaining across the eco system. I think it will require simply duplicating all endpoints and then having the `cloud_storage::sync` and `cloud_storage::async` modules be behind a feature flag. If you have thoughts on this I'd love to hear them!

**Comment by ThouCheese** [comment]
Version 0.5 is now on crates.io! All functions have been ported ported to an async version. I have made a slight deviation from you PR in that instead of each function having a corresponding `function_async`, instead each function has a `function_sync`. This makes the async version the "default", which I think is sensible. Thank you for your work here Carol!
