### ISSUE TITLE
Can we download a file as a stream of bytes?

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [ThouCheese/cloud-storage-rs#15]
Thanks for this awesome, easy to use library. I'm a beginner and the ability to just have something work with few lines of code is a great feeling. I was looking at the Object API, and it seems like we can download the file as a `vec<u8>`, which if I'm not wrong, will download the entire file into memory? Is there any interest in supporting a streaming download? I did notice the download_url API. Is that the recommended way to download large files?

**Comment by ThouCheese** [comment]
Currently it is not possible to download a file in a streamed manner. This is very simple to add however using Reqwest's `Response::bytes_stream`. If you need it I can add it later today, or you can do it yourself 👍

**Comment by ArulselvanMadhavan** [comment]
@ThouCheese Thanks for pointing out how to do it. I'd like to take a shot at it and submit a PR

**Comment by ArulselvanMadhavan** [comment]
@ThouCheese Looks like the ```rust Response::bytes_stream``` is not available in the `blocking` module version of `Response`. I see a PR for adding async support. Should I wait until that is added? If there is another way, let me know

**Comment by ThouCheese** [comment]
@ArulselvanMadhavan you are right, I hadn't noticed that I was looking at `reqwest::async`. As far as I can tell, this is then blocked on building the async feature into the library. I have some time to work on it tonight, but I'd have to coordinate with @carols10cents since I don't know how far along she is, and it would be silly to do the work twice. I have created a branch called `feat/async`, @carols10cents, would you be willing to create a pull request to merge what you currently have in there?

**Comment by carols10cents** [comment]
@ThouCheese Sure! I've opened the work I've done so far at https://github.com/ThouCheese/cloud-storage-rs/pull/16.

**Comment by ThouCheese** [comment]
This is now supported with version 0.5.2! See [the docs](https://docs.rs/cloud-storage/0.5.2/cloud_storage/struct.Object.html#method.download_streamed)
