### ISSUE TITLE
Lazy SERVICE_ACCOUNT

### ISSUE THREAD

**Issue by ernestas-poskus** [ThouCheese/cloud-storage-rs#26]
At the moment service account is initialized lazily, this makes things inconvenient. I would like to pass json string with all credentials during compile time. One option is to wrap SERVICE_ACCOUNT into Mutex then it would be possible to initialize it at the beginning of the program manually but this solution is not elegant either. Other option could global state/context initialized by the user at any point in time and passed as a reference to the function that consumes SERVICE_ACCOUNT and TOKEN_CACHE.
What do you think?

**Comment by ThouCheese** [comment]
Can you elaborate on why having a lazily read service account is inconvenient for you?

Some thoughts:
If you want to initialize the SERVICE_ACCOUNT manually, you also need to consider what behaviour the program should exhibit when you for example try to create a bucket without first configuring the SERVICE_ACCOUNT. Currently the program panics if you do not configure a service account, but if we go down the path of using a programmatically set service account, then it would no longer be a configuration issue, but rather a programming error. This makes it less viable to just panic, since panics represent unrecoverable errors, and the programmer may just have forgotten to call something like `cloud_storage::set_account`.

**Comment by ernestas-poskus** [comment]
I will get over this, manual initialization is not worth added complexity.

**Comment by ollyde** [comment]
@ThouCheese our creds are stored in an env file that is loaded on application load, there's no service account file. Would be nice to pass in details manually.
